trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DB_PASSWORD: "12345"

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building application..."

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying application..."
    - script: echo "DB_PASSWORD = $(DB_PASSWORD)"